FROM postgres:12.3-alpine
# Define database arguments that can be passed in from compose file
ARG ROOT_PASSWORD
ARG DATABASE
ARG USER
ARG PASSWORD

# Now add arguments to environment
ENV POSTGRES_PASSWORD=$PASSWORD
ENV POSTGRES_USER=$USER
ENV POSTGRES_DB=$DATABASE

# Get schema into container to build database
ADD ./schemas/postgres/*.sql /docker-entrypoint-initdb.d/
